; Dies ist eine Exportdatei für Einstellungen des WordPress SEO-Plugins von Yoast.com - http://yoast.com/wordpress/seo/ 

[wpseo]
ms_defaults_set = "1"
version = "1.1.9"
ignore_tour = "ignore"

[wpseo_indexation]
0 = 

[wpseo_permalinks]

[wpseo_titles]
ignore_blog_public_warning = 
ignore_tour = "ignore"
ignore_page_comments = 
ignore_permalink = 
ms_defaults_set = "1"
forcerewritetitle = "on"
title-home = "%%sitename%% - %%sitedesc%%"
metadesc-home = "Hi, ich bin Maik (25) aus Hamburg und dies ist mein privater Blog."
title-post = "%%title%% | %%sitename%% - %%sitedesc%%"
metadesc-post = "%%excerpt%%"
title-page = "%%title%% | %%sitename%% - %%sitedesc%%"
metadesc-page = "%%excerpt%%"
title-attachment = "%%title%% | %%sitename%% - %%sitedesc%%"
metadesc-attachment = "%%caption%%"
title-wiki = "Wiki  | %%sitename%% - %%sitedesc%%"
metadesc-wiki = 
title-feedback = 
metadesc-feedback = 
title-category = "%%category%% | %%page%% | %%sitename%% - %%sitedesc%%"
metadesc-category = "%%category_description%%"
title-post_tag = "%%tag%% | %%page%% | %%sitename%% - %%sitedesc%%"
metadesc-post_tag = "%%tag_description%%"
title-sprache = "%%category%% | %%page%% | %%sitename%% - %%sitedesc%%"
metadesc-sprache = "%%category_description%%"
title-tags = "%%tag%% | %%page%% | %%sitename%% - %%sitedesc%%"
metadesc-tags = "%%tag_description%%"
title-author = "Autor: %%name%% | %%sitename%% - %%sitedesc%%"
metadesc-author = 
title-archive = 
metadesc-archive = 
title-search = "%%searchphrase%%  | %%sitename%% - %%sitedesc%%"
title-404 = "404 Seite nicht gefunden.  | %%sitename%% - %%sitedesc%%"
title-ptarchive-wiki = 
metadesc-ptarchive-wiki = 

[wpseo_rss]
ignore_blog_public_warning = 
ignore_tour = "ignore"
ignore_page_comments = 
ignore_permalink = 
ms_defaults_set = "1"
rssbefore = 
rssafter = "<a href="http://www.amazon.de/gp/product/B005890FUI/ref=as_li_ss_tl?ie=UTF8&tag=buntepixelorg-21&linkCode=as2&camp=1638&creative=19454&creativeASIN=B005890FUI"><img src="https://dl.dropbox.com/u/3404413/ads/kindle.png" /></a>
<br/>
<hr />
<p>© Maik for <a href="http://buntepixel.org">buntepixel.org</a> 2012. </p>
<p><small>Dieser Artikel unterliegt meinem Copyright. Jegliche kommerzielle Nutzung und Einbindung auf anderen Websites nur nach schriftlicher Genehmigung von buntepixel.org.</small></p><br/>
"

[wpseo_internallinks]
ignore_blog_public_warning = 
ignore_tour = "ignore"
ignore_page_comments = 
ignore_permalink = 
ms_defaults_set = "1"
breadcrumbs-sep = 
breadcrumbs-home = 
breadcrumbs-prefix = 
breadcrumbs-archiveprefix = 
breadcrumbs-searchprefix = 
breadcrumbs-404crumb = 
post_types-post-maintax = "category"
post_types-wiki-maintax = "sprache"
taxonomy-sprache-ptparent = "wiki"
taxonomy-tags-ptparent = 
breadcrumbs-boldlast = "on"

[wpseo_xml]
ignore_blog_public_warning = 
ignore_tour = "ignore"
ignore_page_comments = 
ignore_permalink = 
ms_defaults_set = "1"
enablexmlsitemap = "on"
xml_ping_yahoo = "on"
xml_ping_ask = "on"
post_types-feedback-not_in_sitemap = "on"

[wpseo_social]
opengraph = 
fb_pageid = 
fb_adminid = 
fb_appid = 
fbconnectkey = "35f3aa1197ef4a75696904df8a29ebbe"
